devarts/devarts/Controllers/KennelController.cs
using devarts.Helpers;
using devarts.Models;
using devarts.Repositories;
using NLog;
using NLog.Fluent;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace devarts.Controllers
{
    [Authorize]
    [LayoutInjecter("_adminLayout")]
    public class KennelController : Controller
    {

        private KennelRepository _kennelRepo;
        private KennelDbContext _db;
        private static Logger nLog = LogManager.GetCurrentClassLogger();

        public KennelController()
        {
            _kennelRepo = new KennelRepository();
            _db = new KennelDbContext();
            ViewBag.AvailableStatusDropdown = AvailableStatusDropdown();
        }

        public List<SelectListItem> DogSex()
        {
            List<SelectListItem> entryType = new List<SelectListItem>();
            entryType.Add(new SelectListItem { Text = "Suka", Value = "False" });
            entryType.Add(new SelectListItem { Text = "Samiec", Value = "True" });            

            return entryType;
        }

        public List<SelectListItem> GetBootstrapColumn()
        {
            List<SelectListItem> bootstrapCol = new List<SelectListItem>();
            bootstrapCol.Add(new SelectListItem { Text = "Cały rząd (1 element)", Value = "col-lg-12" });
            bootstrapCol.Add(new SelectListItem { Text = "1/2 rzędu (2 elementy)", Value = "col-lg-6" });
            bootstrapCol.Add(new SelectListItem { Text = "1/3 rzędu (3 elementy)", Value = "col-lg-4" });

            return bootstrapCol;
        }

        public List<SelectListItem> AvailableStatusDropdown()
        {
            List<SelectListItem> currency = new List<SelectListItem>();
            currency.Add(new SelectListItem { Text = "--- empty ---", Value = "" });
            currency.Add(new SelectListItem { Text = "AVAILABLE", Value = "AVAILABLE" });
            currency.Add(new SelectListItem { Text = "RESERVED", Value = "RESERVED" });
            currency.Add(new SelectListItem { Text = "PRE-RESERVED", Value = "PRE-RESERVED" });
            currency.Add(new SelectListItem { Text = "SOLD", Value = "SOLD" });
            currency.Add(new SelectListItem { Text = "UNDER OBSERVATION", Value = "UNDER OBSERVATION" });
            currency.Add(new SelectListItem { Text = "STAY WITH US", Value = "STAY WITH US" });
            return currency;
        }

        public List<SelectListItem> GetLetters()
        {
            List<SelectListItem> bootstrapCol = new List<SelectListItem>();
            for (char c = 'A'; c <= 'Z'; c++)
            {
                bootstrapCol.Add(new SelectListItem { Text = c.ToString(), Value = c.ToString() });
            }            

            return bootstrapCol;
        }

        public ActionResult Index()
        {
            var dogBreeds = _kennelRepo.GetAllDogBreed();
            var dogs = _kennelRepo.GetAllDogs();
            var litters = _kennelRepo.GetAllLitters();

            var breedAndDogs = new BreedDogLitterViewModel();
            breedAndDogs.dogBreeds = dogBreeds;
            breedAndDogs.dogs = dogs;
            breedAndDogs.litters = litters;

            //szybka konwersja daty
            //foreach (var dpos in dogs)
            //{
            //    dpos.BornDateDateTime = DateTime.Parse(dpos.BornDate);
            //    TryUpdateModel(dpos);
            //    _kennelRepo.SaveChanges();
            //}

            //var filePath = Path.Combine(HostingEnvironment.MapPath("~/Dogs/ItalianGreyhound/" + "Lea" + "/" + "m1.jpg"));
            //var dirPath = Path.Combine(HostingEnvironment.MapPath("~/Dogs/ItalianGreyhound/" + "Lea" + "/" + "X"));
            //if (System.IO.File.Exists(filePath) == true)
            //{
            //    System.IO.File.Delete(filePath);
            //    System.IO.Directory.Delete(dirPath);
            //    return View(breedAndDogs).WithSuccess(this, "Okej", "Ten plik istnieje");
            //}
            //else
            //{
            //    return View(breedAndDogs).WithError(this, "NIE!", "Ten plik nie istnieje");
            //}

            return View(breedAndDogs);
        }

        /// RASY

        [HttpGet]
        public ActionResult AddBreed()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddBreed(DogBreed model)
        {
            if (ModelState.IsValid)
            {
                var addBreed = new DogBreed();

                addBreed.BreedSpeciesName = model.BreedSpeciesName;
                addBreed.BreedSpeciesDisplayName = model.BreedSpeciesDisplayName;
                addBreed.BreedSpeciesDisplayNameEng = model.BreedSpeciesDisplayNameEng;
                addBreed.BreedDescription = model.BreedDescription;
                addBreed.BreedLink = model.BreedLink;

                addBreed.CreateDate = DateTime.Now.ToString();
                addBreed.Visibility = true;

                _kennelRepo.AddDogBreed(addBreed);
                _kennelRepo.SaveChanges();

                return RedirectToAction("Index").WithSuccess(this, "Gratulacje", "Rasa psa została dodana!");
            }
            return View();
        }

        /// PSY W RASACH
        
        [HttpGet]        
        public ActionResult AddDog(int id)
        {
            ViewBag.DogSex = DogSex();

            try
            {                
                var breed = _kennelRepo.GetDogBreedById(id);
                var dog = new Dog();

                if (breed != null)
                {                    
                    ViewBag.BreedName = breed.BreedSpeciesDisplayName;                    
                    dog.BreedLink = breed.BreedLink;

                    // pobieranie ID kolejnego rekordu przed submitem
                    var dogNextId = _kennelRepo.GetAllDogs().OrderByDescending(o => o.Id).FirstOrDefault();
                    if (dogNextId != null)
                    {
                        TempData["ProbablyNextDogId"] = dogNextId.Id + 1;
                    }
                    else
                    {
                        TempData["ProbablyNextDogId"] = 1;
                    }

                    return View(dog);
                }
                else
                {
                    return RedirectToAction("Index").WithError(this, "Błąd", "<br>Nie znaleziono rasy o podanym ID.<br> Nie można dodać psa.");
                }
            }
            catch
            {
                return RedirectToAction("Index").WithError(this,"Błąd", "<br>Nie rozpoznano ID rasy - nie można dodać zwierzęcia.");
            }            
        }

        [HttpPost]
        public ActionResult AddDog(int id, Dog dogModel)
        {
            ViewBag.DogSex = DogSex();
            string dateTime = DateTime.Now.ToString();

            try
            {
                if (ModelState.IsValid)
                {
                    var breed = _kennelRepo.GetDogBreedById(id);

                    var newDog = new Dog();
                    newDog.SpeciesId = breed.Id;

                    // ustawianie zdjęcia głównego psa
                    var mainImage = _kennelRepo.GetImagesByDogLink(dogModel.DogLink).FirstOrDefault();                    
                    newDog.ImageId = mainImage.Id;
                    newDog.MainPicture = mainImage.ImageFileName;

                    // STANDARDOWE DANE
                    newDog.BreedLink = dogModel.BreedLink;
                    newDog.DogLink = dogModel.DogLink;
                    newDog.DogName = dogModel.DogName;
                    newDog.DogPetName = dogModel.DogPetName;
                    newDog.BornDate = dogModel.BornDate;
                    newDog.BornDateDateTime = DateTime.ParseExact(dogModel.BornDate, "dd.MM.yyyy", null);
                    newDog.DeathDate = dogModel.DeathDate;
                    newDog.CauseOfDeath = dogModel.CauseOfDeath;
                    newDog.DogColour = dogModel.DogColour;
                    newDog.DogSex = dogModel.DogSex;
                    newDog.DogDescription = dogModel.DogDescription;

                    // DANE HODOWLANE
                    newDog.Height = dogModel.Height;
                    newDog.Weight = dogModel.Weight;
                    newDog.CoursingLicenceNumber = dogModel.CoursingLicenceNumber;
                    newDog.BloodlineNumber = dogModel.BloodlineNumber;
                    newDog.DepartmentNumber = dogModel.DepartmentNumber;
                    newDog.ChipNumber = dogModel.ChipNumber;

                    // POCHODZENIE PSA
                    newDog.BreedName = dogModel.BreedName;
                    newDog.OwnerName = dogModel.OwnerName;
                    newDog.OwnerContact = dogModel.OwnerContact;
                    newDog.BreedArchiveUrl = dogModel.BreedArchiveUrl;
                    newDog.DogFatherName = dogModel.DogFatherName;
                    newDog.DogMotherName = dogModel.DogMotherName;
                    newDog.DogFatherBreedName = dogModel.DogFatherBreedName;
                    newDog.DogMotherBreedName = dogModel.DogMotherBreedName;
                    newDog.DogFatherUrl = dogModel.DogFatherUrl;
                    newDog.DogMotherUrl = dogModel.DogMotherUrl;
                    newDog.DogFatherCountry = dogModel.DogFatherCountry;
                    newDog.DogMotherCountry = dogModel.DogMotherCountry;
                    newDog.DogFatherCity = dogModel.DogFatherCity;
                    newDog.DogMotherCity = dogModel.DogMotherCity;

                    // BADANIA
                    newDog.DogMedicalDescription = dogModel.DogMedicalDescription;

                    // OSIĄGNIĘCIA
                    newDog.DegreeDescription = dogModel.DegreeDescription;
                    newDog.AchievementsDescription = dogModel.AchievementsDescription;

devarts/devarts/Views/Kennel/AddBreed.cshtml
@model devarts.Models.DogBreed

@Scripts.Render("~/bundles/summernote")
@Styles.Render("~/content/summernote")

<script>

    $(document).ready(function () {
        $.validator.setDefaults({
            ignore: []
        });

        $('#entryContent').summernote({
            onKeyup: function (e) {
                $("#entryContent").val($("#entryContent").code());
            },
            height: 300,
        });

        $("#BreedLink").keyup(function () {
            var val = $("#BreedLink").val();
                        var mask = "^[A-Za-z0-9-_]+$";

                        $.getJSON("@Url.Action("CheckBreedLinkExists","AjaxKennel")", { breedLink: val }, function (res) {
                            if (res == true) {
                                if ($("#BreedLink").val().match(mask)) {
                                    $("#validateUrl").html("<p style='font-size:larger;'><span class='label label-danger'><i class='fa fa-lock'></i> Taki link już istnieje. Podaj inną wartość.</span></p>");
                                }
                            }
                            else {
                                if ($("#BreedLink").val().match(mask)) {
                                    $("#validateUrl").html("<p style='font-size:larger;'><span class='label label-success'><i class='fa fa-check'></i> Link pasuje :)</span></p>");
                                }
                                else {
                                    if ($("#BreedLink").val() != "" && $("#DogLink").val() != null) {
                                        $("#validateUrl").html("<p style='font-size:larger;'><span class='label label-danger'><i class='fa fa-warning'></i> Błąd - dozwolone litery (bez polskich znaków), myślniki i cyfry.</span><br>"
                                            + "<span class='label label-default'>Poprawne przykłady</span> - "
                                            + "<span class='label label-success'>moj-nowy-post-12-03-2018</span> | "
                                            + "<span class='label label-success'>krotki-artykul-wprowadzajacy</span> | "
                                            + "<span class='label label-success'>wygrana-01022018</span>"
                                            + "</p>");
                                    } else {
                                        $("#validateUrl").html("<p style='font-size:larger;'><span class='label label-danger'><i class='fa fa-info-circle'></i> Wypełnienie tego pola jest niezbędne - dozwolone litery (bez polskich znaków), myślniki i cyfry/liczby</span></p>");
                                    }
                                }
                            }
                        });
                    });
    });
</script>

<div class="row">
    <div class="x_panel">
        <div class="x_title">
            <h2><i class="fa fa-bars"></i><small> Dodawanie rasy</small></h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="col-lg-12">
                <p>Dodanie rasy jest wymagane jeśli zamierzasz dodawać psy do swojej hodowli. Po dodaniu rasy, którą hodujesz będziesz w stanie przypisać do niej zwierzę.</p>
            </div>
            <div class="col-lg-12">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="x-panel">
                                @using (@Html.BeginForm("AddBreed", "Kennel", FormMethod.Post, new { @id = "form1", @enctype = "multipart/form-data" }))
                                {@Html.ValidationSummary()

                                <div class="form-group">
                                    @Html.LabelFor(model => model.BreedSpeciesName, new { @style = "font-weight: bold;" })
                                    <div class="cols-sm-10">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
                                            @Html.TextBoxFor(model => model.BreedSpeciesName, new { @class = "form-control" })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.BreedSpeciesName)
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.BreedSpeciesDisplayName, new { @style = "font-weight: bold;" })
                                    <div class="cols-sm-10">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
                                            @Html.TextBoxFor(model => model.BreedSpeciesDisplayName, new { @class = "form-control" })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.BreedSpeciesDisplayName)
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.BreedSpeciesDisplayNameEng, new { @style = "font-weight: bold;" })
                                    <div class="cols-sm-10">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
                                            @Html.TextBoxFor(model => model.BreedSpeciesDisplayNameEng, new { @class = "form-control" })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.BreedSpeciesDisplayNameEng)
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.BreedDescription, new { @style = "font-weight: bold;" })
                                    <div class="cols-sm-10">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
                                            @Html.TextBoxFor(model => model.BreedDescription, new { @class = "form-control" })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.BreedDescription)
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.BreedLink, new { @style = "font-weight: bold;" })
                                    <div class="cols-sm-10">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
                                            @Html.TextBoxFor(model => model.BreedLink, new { @class = "form-control", pattern = "^[A-Za-z0-9-]+$", maxlength = "50", placeholder = "ItalianGreyhound, Borzoi, AiredaleTerrier..." })
                                        </div>
                                        <div id="validateUrl" class="primary"><p style='font-size:larger;'><span class='label label-danger'><i class='fa fa-info-circle'></i> Wypełnienie tego pola jest niezbędne - dozwolone litery (bez polskich znaków), myślniki i cyfry/liczby</span></p></div>
                                    </div>
                                </div>

                                <div class="x-panel text-center">
                                    <button type="submit" id="saveAll" class="btn btn-lg btn-primary"><i class="fa fa-check"></i> Dodaj rasę</button>
                                </div>
                            }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

devarts/devarts/Views/Kennel/Litters.cshtml
@Scripts.Render("~/bundles/jquery")
@Styles.Render("~/Content/font-awesome.css")

@Styles.Render("~/Content/DataTables")
@Scripts.Render("~/Scripts/KennelDataTables")

<script>
    function passwordChange() {
        $(document).ready(function () {
            $("#pswdFrm").modal('show');
        });
    };

    $("#closbtn").click(function () {
        $('#myModal').modal('hide');
    });

    function newAlert(type, title, message) {
        $("#alert-area").css("display", "none");
        $("#alert-area").html($("<br><br><div class='alert-message alert alert-" + type + " fade in'>" + '<button type="button" class="close" data-dismiss="alert">&times;</button><strong>' + title + '</strong> ' + message + "</div>"));
        $("#alert-area").fadeIn();
        $(".alert-message").delay(3000).fadeOut("slow", function () { $(this).remove(); });
    }

    $(document).ready(function () {
        $("#btnRemoveStatistics").click(function () {
            var table = $('#statisticDataTable').DataTable();
            $.ajax(
                {
                    type: "GET",
                    url: "/Admin/RemoveStatisticRecords"// Controller/View
                    //data: { //Passing data
                    //    //Reading text box values using Jquery
                    //    Line: $("#txtLine").val(),
                    //    Supplier: $("#txtSupplier").val()
                    //}
                }).success(function () {
                    table.ajax.reload();
                    newAlert('success', 'Sukces', 'Lista odwiedzin została skasowana.');
                }).error(function () {
                    table.ajax.reload();
                    newAlert('danger', 'Błąd', 'Coś poszło nie tak.');
                });
        });

        $("#btnRemoveTracing").click(function () {
            var table = $('#tracingDataTable').DataTable();
            $.ajax(
                {
                    type: "GET",
                    url: "/Admin/RemoveTracingRecords"// Controller/View
                    //data: { //Passing data
                    //    //Reading text box values using Jquery
                    //    Line: $("#txtLine").val(),
                    //    Supplier: $("#txtSupplier").val()
                    //}
                }).success(function () {
                    table.ajax.reload();
                    newAlert('success', 'Sukces', 'Lista tras użytkowników została wyczyszczona.');
                }).error(function () {
                    table.ajax.reload();
                    newAlert('danger', 'Błąd', 'Coś poszło nie tak.');
                });
        });
    });
</script>

<style>
    /*styl pozycjonujący rodzaj urządzenia*/
    .dt-body-center {
        text-align: center;
    }

    #alert-area {
        display: none;
    }
</style>
<br />
<div id="alert-area"></div>
<div id="alerts">
</div>
<div class="row">
    <div class="container">
        <br />
        <div class="row">
            <div class="col-lg-12">
                <div class="x_panel">
                    <ol class="breadcrumb">
                        <li>
                            @Html.ActionLink("Strona Główna", "Index", "Home")
                        </li>
                        <li>
                            <a href="~/Admin/AdminPanel">Panel administratora</a>
                        </li>
                        <li>
                            <a href="~/Kennel/Index">Hodowla</a>
                        </li>
                        <li>
                            <a href="~/Kennel/Litters">Mioty</a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="x_panel">
        <div class="x_title">
            <h1>@ViewBag.siteName <small>@ViewBag.ownerFirstName @ViewBag.OwnerSurName</small></h1>
            <h5><strong>@ViewBag.devaArtsCMS</strong></h5>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <h3>Mioty hodowli</h3>
            <p>Zarządzanie miotami i szczeniętami przypisanymi do hodowli.</p>
        </div>
    </div>
</div>


<div class="row">
    @Html.Partial("_littersView")
</div>

devarts/devarts/Views/Kennel/_imagesByDog.cshtml
@model devarts.Models.DogWithImages
<style>
    .btn {
        margin: 3px !important;
    }

    .setImageIndex{
        max-width: 100px;
    }
</style>
<div class="form-group">
    <div class="row">
        <div class="col-lg-4">
            <h4 class="text-center">Główne</h4>
            <div>
                <img alt="" src="/Dogs/@Model.dog.BreedLink/@Model.dog.DogLink/@Model.dog.MainPicture" id="dog" style="width:100%">
            </div>
        </div>
        <div class="col-lg-8">
            <div class="row">
                <h4 class="text-center">Przypisane do zwierzęcia</h4>
                @{
                    int i = 0;
                }
                @foreach (var pos in Model.images)
                {
                    if (i != 0 && i % 6 == 0)
                    {
                    @:</div>
                    @:<div class="row">
                    }
                    <div class="col-lg-2" style="padding-bottom:5px;">                       
                        <a href="@Url.Action("SetDogImageAsMainImage", "Kennel", new { dogLink = Model.dog.DogLink, mainImageId = pos.Id })" data-placement="top" data-toggle="tooltip" data-original-title="Ustaw jako zdjęcie główne" class="btn btn-xs btn-primary"><i class="fa fa-image"></i></a>                        
                        <a href="@Url.Action("RemoveImageFromDog", "Kennel", new { imgFileName = pos.ImageFileName, dogLink = Model.dog.DogLink })" data-placement="top" data-toggle="tooltip" data-original-title="Usuń z serwera i bazy danych" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>                        
                        <img alt="@pos.ImageAlt" src="/Dogs/@Model.dog.BreedLink/@Model.dog.DogLink/@pos.ImageFileName" style="width:100%" />
                        <span><small>Indeks zdjęcia (enter)</small></span>
                        @Html.TextBoxFor(model => pos.ImageIndex, new { @class="setImageIndex", data_image_id = pos.Id })<br />
                        <span><small>Tekst alternatywny (enter)</small></span>
                        @Html.TextBoxFor(model => pos.ImageAlt, new { @class="setAltValue", data_image_id = pos.Id })
                        <hr />
                    </div>
                    i++;
                }
            </div>
        </div>
    </div>
</div>

devarts/devarts/Views/Kennel/_imagesByLitter.cshtml
@model devarts.Models.LitterWithImagesAndDog
<style>
    .btn {
        margin: 3px !important;
    }

    .setImageIndex {
        max-width: 100px;
    }
</style>
<div class="form-group">
    <div class="row">
        <div class="col-lg-4">
            <h4 class="text-center">Główne</h4>
            <div>
                <img alt="" src="/Litters/@Model.litter.BreedLink/@Model.litter.LitterLink/@Model.litter.MainPicture" id="dog" style="width:100%">
            </div>
        </div>
        <div class="col-lg-8">
            <div class="row">
                <h4 class="text-center">Przypisane do miotu</h4>
                @{
                    int i = 0;
                }
                @foreach (var pos in Model.litterImages)
                {
                    if (i != 0 && i % 6 == 0)
                    {
                    @:</div>
                    @:<div class="row">
                    }
                          <div class="col-lg-2" style="padding-bottom:5px;">
                              <a href="@Url.Action("SetLitterImageAsMainImage", "Kennel", new { litterLink = Model.litter.LitterLink, mainImageId = pos.Id })" data-placement="top" data-toggle="tooltip" data-original-title="Ustaw jako zdjęcie główne" class="btn btn-xs btn-primary"><i class="fa fa-image"></i></a>
                              <a href="@Url.Action("RemoveImageFromLitter", "Kennel", new { imgFileName = pos.ImageFileName, litterLink = Model.litter.LitterLink })" data-placement="top" data-toggle="tooltip" data-original-title="Usuń z serwera i bazy danych" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                              <a href="@Url.Action("SetFatherLitter", "Kennel", new { litterLink = Model.litter.LitterLink,  mainImageId = pos.Id })" data-placement="top" data-toggle="tooltip" data-original-title="Ustaw jako zdjęcie ojca miotu" class="btn btn-xs btn-success"><i class="fa fa-camera-retro"></i></a>
                              <img alt="@pos.ImageAlt" src="/Litters/@Model.litter.BreedLink/@Model.litter.LitterLink/@pos.ImageFileName" style="width:100%" />
                              <span><small>Indeks zdjęcia (enter)</small></span>
                              @Html.TextBoxFor(model => pos.ImageIndex, new { @class = "setImageIndex", data_image_id = pos.Id })<br />
                              <span><small>Tekst alternatywny (enter)</small></span>
                              @Html.TextBoxFor(model => pos.ImageAlt, new { @class = "setAltValue", data_image_id = pos.Id })
                              <hr />
                          </div>
                    i++;
                }
            </div>
        </div>
    </div>
</div>

devarts/devarts/Views/Kennel/_puppiesByPuppie.cshtml
@model devarts.Models.PuppyAndImages
<style>
    .btn {
        margin: 3px !important;
    }

    .setImageIndex {
        max-width: 100px;
    }
</style>
<div class="form-group">
    <div class="row">
        <div class="col-lg-4">
            <h4 class="text-center">Główne</h4>
            <div>
                <img alt="" src="/Puppies/@Model.puppy.BreedLink/@Model.puppy.PuppyLink/@Model.puppy.MainPicture" id="dog" style="width:100%">
            </div>
        </div>
        <div class="col-lg-8">
            <div class="row">
                <h4 class="text-center">Przypisane do zwierzęcia</h4>
                @{
                    int i = 0;
                }
                @foreach (var pos in Model.puppyImages)
                {
                    if (i != 0 && i % 6 == 0)
                    {
                    @:</div>
                    @:<div class="row">
                    }
                    <div class="col-lg-2" style="padding-bottom:5px;">
                        <a href="@Url.Action("SetPuppyImageAsMainImage", "Kennel", new { breedLink = Model.puppy.BreedLink, puppyLink = Model.puppy.PuppyLink, mainImageId = pos.Id })" data-placement="top" data-toggle="tooltip" data-original-title="Ustaw jako zdjęcie główne" class="btn btn-xs btn-primary"><i class="fa fa-image"></i></a>
                        <a href="@Url.Action("RemoveImageFromPuppy", "Kennel", new { imgFileName = pos.ImageFileName, breedLink = Model.puppy.BreedLink, litterLink = Model.puppy.LitterLink, puppyLink = Model.puppy.PuppyLink })" data-placement="top" data-toggle="tooltip" data-original-title="Usuń z serwera i bazy danych" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                        <img alt="@pos.ImageAlt" src="/Puppies/@Model.puppy.BreedLink/@Model.puppy.PuppyLink/@pos.ImageFileName" style="width:100%" />
                        <span><small>Indeks zdjęcia (enter)</small></span>
                        @Html.TextBoxFor(model => pos.ImageIndex, new { @class = "setPuppyImageIndex", data_image_id = pos.Id })<br />
                        <span><small>Tekst alternatywny (enter)</small></span>
                        @Html.TextBoxFor(model => pos.ImageAlt, new { @class= "setAltPuppyValue", data_image_id = pos.Id })
                        <hr />
                    </div>
                    i++;
                }
            </div>
        </div>
    </div>
</div>