devarts/devarts/Controllers/ReproductionController.cs
using devarts.Helpers;
using devarts.Models;
using devarts.Repositories;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devarts.Controllers
{
    [LayoutInjecter("_adminLayout")]
    [Authorize]
    public class ReproductionController : Controller
    {
        AssistantRepository _assistRepo;
        KennelRepository _kennelRepo;
        private static Logger nLog = LogManager.GetCurrentClassLogger();

        public ReproductionController()
        {
            _assistRepo = new AssistantRepository();
            _kennelRepo = new KennelRepository();
        }

        public List<SelectListItem> BitchesList()
        {
            List<SelectListItem> dogSelect = new List<SelectListItem>();
            var allBitches = _kennelRepo.GetAllDogs().Where(d => d.DogSex == false).OrderBy(d => d.BornDate);
            string dogName;
            foreach (var dog in allBitches)
            {
                dogName = dog.DogName.Substring(0, 1).ToUpper() + dog.DogName.Substring(1, dog.DogName.Length - 1).ToLower();
                dogSelect.Add(new SelectListItem { Text = dogName, Value = dogName });
            }

            return dogSelect;
        }

        public ActionResult Index()
        {                                   
            ViewBag.BitchesList = BitchesList();

            List<ReproductionAndDog> returnList = new List<ReproductionAndDog>();
            var allBitches = _kennelRepo.GetAllDogs().Where(d => d.DogSex == false).OrderBy(d => d.BornDate);

            foreach(var newPos in allBitches)
            {
                var searchInReproductions = _assistRepo.GetReproductionByLastDogName(newPos.DogName);
                if (searchInReproductions != null)
                {
                    ReproductionAndDog newRep = new ReproductionAndDog();
                    newRep.Dog = newPos;
                    newRep.Reproduction = searchInReproductions;
                    returnList.Add(newRep);
                }                
            }

            ReproductionStatisticView returnView = new ReproductionStatisticView
            {
                Reproduction = new Reproduction(),
                ReproductionAndDog = returnList 
            };
            
            return View(returnView);
        }            

        [HttpPost]
        public JsonResult AddReproduction(Reproduction model)
        {            
            if (ModelState.IsValid)
            {
                Reproduction rep = new Reproduction();
                DateTime createDate = DateTime.Now;
                rep.DogName = model.DogName;
                rep.FatherName = model.FatherName;
                rep.EstrusStartDate = model.EstrusStartDate;                
                rep.MatingDate_First = model.MatingDate_First;

                // pola muszą być wypełnione, bo inaczej nie można dodawać pozycji
                rep.RutStartDate = createDate;
                rep.EstrusEndDate = createDate;
                rep.RutEndDate = createDate;
                rep.MatingDate_Second = createDate;
                rep.MatingDate_Third = createDate;
                rep.EstimationBornDate = createDate;
                rep.NextEstrusDate = createDate;
                rep.DateOfBorn = createDate;

                var searchDog = _kennelRepo.GetAllDogs().FirstOrDefault(d => d.DogName.ToLower() == model.DogName);
                if (searchDog != null)
                {
                    rep.DogId = searchDog.Id;
                } 

                TryUpdateModel(rep);
                _assistRepo.Add(rep);
                _assistRepo.SaveChanges();

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditReproduction(int id)
        {
            ViewBag.BitchesList = BitchesList();
            try
            {
                var editReproduction = _assistRepo.GetReproductionById(id);
                if (editReproduction != null)
                {
                    Reproduction fin = editReproduction;
                    return PartialView("_editReproduction", fin);
                }

                return PartialView("_editReproduction", null);
            }
            catch (Exception ex)
            {
                nLog.Error("Błąd podczas odczytywania okna edytowania cieczek: " + ex.ToString());
                return PartialView("_editReproduction", null).WithError(this, "Błąd", "Błąd: " + ex.ToString());
            }
        }

        [HttpPost]
        public JsonResult EditReproduction(Reproduction model)
        {
            ViewBag.BitchesList = BitchesList();
            try
            {
                var editReproduction = _assistRepo.GetReproductionById(model.Id);
                if (ModelState.IsValid)
                {
                    editReproduction.DogName = model.DogName;
                    
                    TryUpdateModel(editReproduction);
                    _assistRepo.SaveChanges();
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                nLog.Error("Błąd podczas edytowania cieczek: " + ex.ToString());
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        public void RemoveReproduction(int id)
        {
            try
            {
                var repToRemove = _assistRepo.GetReproductionById(id);
                if (repToRemove != null)
                {
                    _assistRepo.Remove(repToRemove);
                    _assistRepo.SaveChanges();
                    Response.StatusCode = 200;
                }
            }
            catch
            {
                // wysłanie do jQuery statusu Error
                Response.StatusCode = 500;
            }
        }
    }
}

devarts/devarts/Views/Reproduction/_addReproduction.cshtml
@model devarts.Models.Reproduction

<div class="modal-dialog">
    <div class="modal-content">
        @using (Ajax.BeginForm("AddReproduction", "Reproduction", new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "patientList",
            LoadingElementId = "loader",
            OnSuccess = "OnSuccessOperations()",
        }, new { Id = "AddReproductionForm" }))
        {           
            @Html.AntiForgeryToken()

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title" id="myModalLabel">
                    <i class="fa fa-paw"></i> Dodawanie
                    <small>cieczki / rui</small>
                </h3>
            </div>
            <div class="modal-body">
                @*<div class="row">
                        <div class="col-lg-12">
                            @Html.ValidationSummary()
                        </div>
                    </div>*@
                <div class="row">
                    <div class="col-lg-12 form-horizontal">
                        <div class="form-group">
                            @Html.LabelFor(model => model.DogName, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
                                    @Html.DropDownListFor(m => Model.DogName, new SelectList(@ViewBag.BitchesList, "Value", "Text"), new { @class = "form-control" })
                                </div>
                            </div>
                            @Html.ValidationMessageFor(model => model.DogName)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.TextBoxFor(model => model.FatherName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.FatherName)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.EstrusStartDate, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.TextBoxFor(model => model.EstrusStartDate, "{0:yyyy.MM.dd HH:mm}", new { @Value = "", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.EstrusStartDate)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MatingDate_First, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.TextBoxFor(model => model.MatingDate_First, "{0:yyyy.MM.dd HH:mm}", new { @Value = "", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MatingDate_First)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-lg-12">
                        <input class="btn btn-danger" type="submit" value="Zapisz">
                        <a href="#" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Zamknij</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    (function ($) {
        $.validator.unobtrusive.adapters.addBool("checkboxrequired", "required");
    }(jQuery));
</script>

devarts/devarts/Views/Reproduction/_reproductionView.cshtml
<style>
    .bolded {
        font-weight: bold;
    }

    .red-bolded {
        color: red;
        font-weight: bold;
        width: 100px !important;
        font-size: 12px;
    }

    .green {
        color: green;
        font-weight: bold;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Lista<small>wszystkich cieczek i kryć</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Settings 1</a>
                            <a class="dropdown-item" href="#">Settings 2</a>
                        </div>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="reproductionDataTable" class="table small" width="100%" cellspacing="0">
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Suka</th>
                            <th>Reproduktor</th>
                            <th>Rozpoczęcie cieczki</th>
                            <th>Pierwsze krycie</th>
                            <th>Narodziny</th>
                            @*<th>Dzień naj. progesteronu</th>
                                <th>Poziom progesteronu</th>*@
                            <th>Komentarz</th>
                            @*<th>Sukces</th>*@
                            <th>Operacje</th>
                        </tr>
                    </tfoot>
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Suka</th>
                            <th>Reproduktor</th>
                            <th>Rozpoczęcie cieczki</th>
                            <th>Pierwsze krycie</th>
                            <th><i class="fa fa-star"></i><br />Narodziny</th>
                            @*<th>Dzień naj. progesteronu</th>
                                <th>Poziom progesteronu</th>*@
                            <th>Komentarz</th>
                            @*<th>Sukces</th>*@
                            <th>Operacje</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="morris-area-chart"></div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>