devarts/devarts/Controllers/FinanceController.cs
using devarts.Helpers;
using devarts.Models;
using devarts.Repositories;
using NLog;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace devarts.Controllers
{
    [LayoutInjecter("_adminLayout")]
    [Authorize]
    public class FinanceController : Controller
    {
        private FinanceRepository _financeRepo;
        private static Logger nLog = LogManager.GetCurrentClassLogger();

        /*        
        Odżywianie
        Leczenie
        Profilaktyka
        Krycia
        Sprzedaż
        Akcesoria
        Wystawy
        Sport
        Inne
        */

        public JsonResult ShowText(string json)
        {
            string jsonr = new JavaScriptSerializer().Serialize(json);
            return Json(jsonr, JsonRequestBehavior.AllowGet);
        }

        public FinanceController()
        {
            _financeRepo = new FinanceRepository();

            ViewBag.Currency = Currency();
            ViewBag.Cathegories = Cathegories();
        }

        public List<SelectListItem> Currency()
        {
            List<SelectListItem> currency = new List<SelectListItem>
            {
                new SelectListItem { Text = "Polski złoty", Value = "PLN" },
                new SelectListItem { Text = "Euro", Value = "EUR" },
                new SelectListItem { Text = "Dolar", Value = "EUR" }
            };
            return currency;
        }

        public List<SelectListItem> Cathegories()
        {
            List<SelectListItem> currency = new List<SelectListItem>
            {
                new SelectListItem { Text = "Odżywianie", Value = "Odżywianie" },
                new SelectListItem { Text = "Leczenie", Value = "Leczenie" },
                new SelectListItem { Text = "Profilaktyka", Value = "Profilaktyka" },
                new SelectListItem { Text = "Krycia", Value = "Krycia" },
                new SelectListItem { Text = "Sprzedaż", Value = "Sprzedaż" },
                new SelectListItem { Text = "Akcesoria", Value = "Akcesoria" },
                new SelectListItem { Text = "Wystawy", Value = "Wystawy" },
                new SelectListItem { Text = "Sport", Value = "Sport" },
                new SelectListItem { Text = "Inne", Value = "Inne" }
            };
            return currency;
        }

        public JsonResult UpdateBarChart(int year)
        {
            FinanceCharts financeCharts = new FinanceCharts();
            var resultFin = financeCharts.YearFinanceBar(year);
            string jsonData = new JavaScriptSerializer().Serialize(resultFin);
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            NBP_API_Helper nbp = new NBP_API_Helper();            
            ViewBag.EUR = nbp.GetCurrencyToday("EUR");
            if (ViewBag.EUR.Contains("404: Brak wyników"))
            {
                ViewBag.EUR = "od 07:00";
            }
            
            nLog.Info("Odczytano kurs euro: " + ViewBag.EUR);
            ViewBag.USD = nbp.GetCurrencyToday("USD");
            if (ViewBag.USD.Contains("404: Brak wyników"))
            {
                ViewBag.USD = "od 07:00";
            }

            nLog.Info("Odczytano kurs dolara: " + ViewBag.USD);

            decimal sumExpense = 0;
            decimal sumNotExpense = 0;

            if (_financeRepo.GetFinances().Where(fin => fin.IsExpense).Count() > 0)
            {
                sumExpense = _financeRepo.GetFinances().Where(fin => fin.IsExpense).Select(fin => fin.Amount).Sum();
            }

            if (_financeRepo.GetFinances().Where(fin => fin.IsExpense == false).Count() > 0)
            {
                sumNotExpense = _financeRepo.GetFinances().Where(fin => fin.IsExpense == false).Select(fin => fin.Amount).Sum();
            }

            ViewBag.Expense = string.Format("{0:#,##0}", sumExpense) + " PLN";
            ViewBag.NotExpense = string.Format("{0:#,##0}", sumNotExpense) + " PLN";

            var nowYear = DateTime.Now.Year;
            FinanceCharts finc = new FinanceCharts();
            ViewBag.monthsNames = finc.YearFinanceBar(nowYear).monthsNames;
            ViewBag.monthsNamesJS = finc.YearFinanceBar(nowYear).monthsNamesJS;
            ViewBag.monthsIncome = finc.YearFinanceBar(nowYear).monthsIncome;
            ViewBag.monthsExpense = finc.YearFinanceBar(nowYear).monthsExpense;

            ViewBag.sumCathegories = finc.YearFinancePie(nowYear).sumCathegories;
            return View();
        }

        [HttpPost]
        public JsonResult AddFinance(Finance model)
        {
            NBP_API_Helper nbp = new NBP_API_Helper();
            ViewBag.EUR = nbp.GetCurrencyToday("EUR"); nLog.Info("Odczytano kurs euro: " + ViewBag.EUR);
            ViewBag.USD = nbp.GetCurrencyToday("USD"); nLog.Info("Odczytano kurs dolara: " + ViewBag.USD);

            if (ModelState.IsValid)
            {
                Finance fin = new Finance();
                DateTime createDate = DateTime.Now;
                fin.Name = model.Name;
                fin.Description = model.Description;

                fin.DateFrom = model.DateFrom;
                fin.DateTo = model.DateTo;
                fin.Cathegory = model.Cathegory;
                fin.Amount = model.Amount;
                fin.CurrencyName = model.CurrencyName;
                fin.IncludeFinance = model.IncludeFinance;
                fin.IsExpense = model.IsExpense;
                
                fin.CreateDate = createDate;
                fin.ModifiedDate = createDate;

                _financeRepo.AddFinance(fin);
                _financeRepo.SaveChanges();
                
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditFinance(int id)
        {
            try
            {
                var editFinance = _financeRepo.GetFinanceById(id);
                if (editFinance != null)
                {
                    Finance fin = editFinance;
                    return PartialView("_editFinance", fin);
                }

                return PartialView("_editFinance", null);
            }
            catch (Exception ex)
            {                
                nLog.Error("Błąd podczas odczytywania okna edytowania finansów: " + ex.ToString());
                return PartialView("_editFinance", null).WithError(this, "Błąd", "Błąd: " + ex.ToString());
            }
        }

        [HttpPost]
        public JsonResult EditFinance(Finance model)
        {
            try
            {
                var editFinance = _financeRepo.GetFinanceById(model.Id);
                if (ModelState.IsValid)
                {                    
                    editFinance.Name = model.Name;
                    editFinance.Description = model.Description;
                    editFinance.DateFrom = model.DateFrom;
                    editFinance.DateTo = model.DateTo;
                    editFinance.Cathegory = model.Cathegory;
                    editFinance.Amount = model.Amount;
                    editFinance.CurrencyName = model.CurrencyName;
                    editFinance.IncludeFinance = model.IncludeFinance;
                    editFinance.IsExpense = model.IsExpense;
                    editFinance.ModifiedDate = DateTime.Now;

                    TryUpdateModel(editFinance);
                    _financeRepo.SaveChanges();
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                nLog.Error("Błąd podczas edytowania finansów: " + ex.ToString());
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        // AJAX-owe wywołanie metody usuwającej daną pozycję finansową
        public void RemoveFinance(int id)
        {
            try
            {
                var finToRemove = _financeRepo.GetFinanceById(id);
                if (finToRemove != null)
                {
                    _financeRepo.RemoveFinance(finToRemove);
                    _financeRepo.SaveChanges();
                    Response.StatusCode = 200;
                }
            }
            catch
            {
                // wysłanie do jQuery statusu Error
                Response.StatusCode = 500;
            }
        }
    }
}

devarts/devarts/Views/Finance/Index.cshtml
@Styles.Render("~/Content/css")
@Styles.Render("~/Content/DataTables")
@Styles.Render("~/Content/font-awesome.css")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/ajaxuntro")
@Scripts.Render("~/Scripts/AssistantDataTables")
@Scripts.Render("~/bundles/devarts")

<br />
<div id="alert-area"></div>
<div id="alerts">
</div>

<div class="container">
    <br />
    <div class="row">
        <div class="col-lg-12">
            <div class="x_panel">
                <ol class="breadcrumb">
                    <li>
                        @Html.ActionLink("Strona Główna", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Panel Administratora", "Index", "Admin")
                    </li>
                    <li>
                        @Html.ActionLink("Asystent Hodowli", "Index", "Admin")
                    </li>
                    <li>
                        <a href="~/Admin/AdminPanel">Finanse hodowli</a>
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        <i class="fa fa-globe"></i> Euro <b>@ViewBag.EUR</b> | Dolar <b>@ViewBag.USD</b><br />
                        <small style="margin-left: 1px">Pobrano z API Narodowego Banku Polskiego</small>
                    </h2><br />
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <h3>Operacje</h3>
                    <p>Co chcesz teraz zrobić?</p>
                    <div class="col-lg-12">
                        <hr />
                        <a href="javaScript:void(0)" class="btn btn-app" id="addPosition"><span class="badge bg-dark-alfa-40"></span><i class="fa fa-money"></i><b>Dodaj...</b></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        <i class="fa fa-globe"></i> Wykres wydatków i przychodów <b>w skali roku</b><br />
                        <small style="margin-left: 1px">Wykres obejmuje rok <b>2022</b></small>
                    </h2><br />
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="x_content" style="height: 181px !important">
                        <canvas id="mybarChartek"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> Zarządzanie finansami
                    <div class="pull-right"></div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div id="morris-area-chart"></div>


                    <ul class="nav small dashboard nav-tabs bar_tabs" id="financeTabs">
                        <li class="active"><a href="#1"><i class="glyphicon glyphicon-import"></i> Zestawienie finansów<small> w formie listy</small></a></li>
                        <li><a href="#2"><i class="glyphicon glyphicon-import"></i> Wykresy<small> i statystyki</small></a></li>
                    </ul>

                    <!-- TAB CONTENT -->
                    <div class="tab-content">


                        <div id="1" class="tab-pane fade in active">
                            <div class="row">
                                <div class="col-lg-12">
                                    @Html.Partial("_financesList")
                                </div>
                            </div>
                        </div>
                        <div id="2" class="tab-pane fade">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="x_panel">
                                        <div class="x_title">
                                            <h2>Wykres <small>Liniowy</small></h2>
                                            <ul class="nav navbar-right panel_toolbox">
                                                <li>
                                                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                                </li>
                                                <li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                        <a class="dropdown-item" href="#">Settings 1</a>
                                                        <a class="dropdown-item" href="#">Settings 2</a>
                                                    </div>
                                                </li>
                                                <li>
                                                    <a class="close-link"><i class="fa fa-close"></i></a>
                                                </li>
                                            </ul>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="x_content" style="height: 300px !important">
                                            <canvas id="lineChartek"></canvas>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="x_panel">
                                        <div class="x_title">
                                            <h2>Pie <small>Chart</small></h2>
                                            <ul class="nav navbar-right panel_toolbox">
                                                <li>
                                                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                                </li>
                                                <li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                        <a class="dropdown-item" href="#">Settings 1</a>
                                                        <a class="dropdown-item" href="#">Settings 2</a>
                                                    </div>
                                                </li>
                                                <li>
                                                    <a class="close-link"><i class="fa fa-close"></i></a>
                                                </li>
                                            </ul>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="x_content">
                                            <canvas id="pieChartek"></canvas>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="x_panel">
                                        <div class="x_title">
                                            <h2>Donut <small>Chart</small></h2>
                                            <ul class="nav navbar-right panel_toolbox">
                                                <li>
                                                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                                </li>
                                                <li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                        <a class="dropdown-item" href="#">Settings 1</a>
                                                        <a class="dropdown-item" href="#">Settings 2</a>
                                                    </div>
                                                </li>
                                                <li>
                                                    <a class="close-link"><i class="fa fa-close"></i></a>
                                                </li>
                                            </ul>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="x_content">
                                            <canvas id="donut"></canvas>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12"></div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-12">
            <div class="x_panel">
                <div class="x_title">
                    <h1>@ViewBag.siteName <small>@ViewBag.ownerFirstName @ViewBag.OwnerSurName</small></h1>
                    <h5><strong>@ViewBag.devaArtsCMS</strong></h5>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content" id="testDiv">
                    <h3>Podsumowanie @*@Html.Raw(Json.Encode(ViewBag.monthsNames))*@</h3>
                    <p><b>Wydatki łącznie: </b><span class="red" style="font-weight: bold">@ViewBag.Expense</span></p>
                    <p><b>Przychody łącznie: </b><span class="green">@ViewBag.NotExpense</span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="hide astra" id="data-container">
        <span id="barChartLabels" data-barChartekLabels="@Json.Encode(ViewBag.monthsNames).Replace("\"", "'")"></span>
        <span id="barChartLabelsJS" data-barchartekjs="@Json.Encode(ViewBag.monthsNamesJS).Replace("\"", "'")"></span>
        <span id="barchartexpense" data-barchartexpense="@Html.Raw(string.Join(",", Json.Encode(ViewBag.monthsExpense)))"></span>
        <span id="barchartincome" data-barchartincome="@Html.Raw(string.Join(",", Json.Encode(ViewBag.monthsIncome)))"></span>
        <span id="urlbarchartupdate" data-urlbarchartupdate="@Url.Action("UpdateBarChart","Finance")"></span>
        <span id="piechartdata" data-piechartdata="@Html.Raw(string.Join(",", Json.Encode(ViewBag.sumCathegories)))"></span>
    </div>

</div>

<div id="addFinanceModal" class="modal fade">
    @Html.Partial("_addFinance")
</div>

<div id="editFinanceModal" class="modal fade">
    <div id='editFinanceModalContent'>
        @Html.Partial("_editFinance")
    </div>
</div>

<script type="text/javascript" src="~/ViewsJS/Finance/Finance.js"></script>

devarts/devarts/Views/Finance/_addFinance.cshtml
@model devarts.Models.Finance

<div class="modal-dialog">
    <div class="modal-content">
        @using (Ajax.BeginForm("AddFinance", "Finance", new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "patientList",
            LoadingElementId = "loader",
            OnSuccess = "OnSuccessOperations()",
        }, new { Id = "AddFinanceForm", autocomplete = "off" }))
        {
            @Html.AntiForgeryToken()

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title" id="myModalLabel">
                    <i class="fa fa-bar-chart"></i> Nowy wydatek
                    <small>/ przychód</small>
                </h3>
            </div>
            <div class="modal-body">
                @*<div class="row">
                        <div class="col-lg-12">
                            @Html.ValidationSummary()
                        </div>
                    </div>*@
                <div class="row">
                    <div class="col-lg-12 form-horizontal">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Name)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Description)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.TextBoxFor(model => model.DateFrom, "{0:yyyy.MM.dd HH:mm}", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DateFrom)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.TextBoxFor(model => model.DateTo, "{0:yyyy.MM.dd HH:mm}", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DateTo)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Cathegory, new { @style = "font-weight: bold;", @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
                                    @Html.DropDownListFor(m => Model.Cathegory, new SelectList(@ViewBag.Cathegories, "Value", "Text"), new { @class = "form-control" })
                                </div>
                                @Html.ValidationMessageFor(model => model.Cathegory)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", @type = "number", @step = "0.01", @placeholder = "W kwocie użyj przecinku zamiast kropki np. 250,50" })
                                @Html.ValidationMessageFor(model => model.Amount)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CurrencyName, new { @style = "font-weight: bold;", @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-pencil fa" aria-hidden="true"></i></span>
                                    @Html.DropDownListFor(m => Model.CurrencyName, new SelectList(@ViewBag.Currency, "Value", "Text"), new { @class = "form-control" })
                                </div>
                                @Html.ValidationMessageFor(model => model.CurrencyName)
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <hr />

                            <div class="col-lg-12 pull-right" style="vertical-align:middle;">
                                @Html.CheckBoxFor(model => model.IncludeFinance, new { @class = "big-checkbox green", @checked = "checked" })
                                <b>
                                    @Html.LabelFor(model => model.IncludeFinance, new { @class = "label-checkbox big-check-box-label", @checked = "checked" })
                                </b>
                            </div>
                            <div class="col-lg-12 pull-right">
                                <hr />
                                @Html.CheckBoxFor(model => model.IsExpense, new { @class = "big-checkbox", @checked = "checked" })
                                <b>
                                    @Html.LabelFor(model => model.IsExpense, new { @class = "label-checkbox big-check-box-label red", @checked = "checked" })
                                </b>
                                <p>Wyczyść to pole jeśli pozycja jest <b class="red">przychodem</b>.</p>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-lg-12">
                        <input class="btn btn-danger" type="submit" value="Zapisz">
                        <a href="#" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Zamknij</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    (function ($) {
        $.validator.unobtrusive.adapters.addBool("checkboxrequired", "required");
    }(jQuery));
</script>

devarts/devarts/Views/Finance/_financesList.cshtml
<div class="panel panel-default">


    <style>
        .bolded {
            font-weight: bold;
        }

        .red-bolded {
            color: red;
            font-weight: bold;
            width: 100px !important;
            font-size: 12px;
        }

        .green {
            color: green;
            font-weight: bold;
        }
    </style>

    <div id="morris-area-chart"></div>
    
    <table id="financeDataTable" class="table small table-striped table-hover" width="100%" cellspacing="0">
        <tfoot>
            <tr>
                <th>Id</th>
                <th>Kwota</th>
                <th>Nazwa</th>
                <th>Opis</th>
                <th>Kategoria</th>
                <th>Od</th>
                <th>Do</th>
                <th>Waluta</th>
                <th>Operacje</th>
            </tr>
        </tfoot>
        <thead>
            <tr>
                <th>Id</th>
                <th>Kwota</th>
                <th>Nazwa</th>
                <th>Opis</th>
                <th>Kategoria</th>
                <th>Od</th>
                <th>Do</th>
                <th>Waluta</th>
                <th>Operacje</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>